### ISSUE TITLE
访问e5.qyi.io error521

### ISSUE THREAD

**Issue by Kevin-2106** [luoye663/e5#19]
Error 521
Ray ID: 71d086c15e27967c • 2022-06-18 02:17:03 UTC
Web server is down

**What happened?**
The web server is not returning a connection. As a result, the web page is not displaying

**Comment by Yumerakk** [comment]
> 

me too

**Comment by luoye663** [comment]
已恢复~

**Comment by amony899** [comment]
https://e5.qyi.io/user/baseSetting
