### ISSUE TITLE
无法删除旧的api应用

### ISSUE THREAD

**Issue by wangp-blog** [luoye663/e5#37]
![image](https://user-images.githubusercontent.com/31883473/222033547-86783a0b-087c-41a4-a9cb-db988cfff74b.png)
点击删除，提示：
![image](https://user-images.githubusercontent.com/31883473/222033599-84588309-29b9-4621-b4da-3faf162b055a.png)

**Comment by orange2008** [comment]
同，无法删除

**Comment by Dell911** [comment]
我也是，作者怎么不修复，也不出来解释下 🤣

**Comment by luoye663** [comment]
已修复。
