### ISSUE TITLE
URI和报错

### ISSUE THREAD

**Issue by tkfanswind** [luoye663/e5#7]
重定向 URI 应该填写什么？ 是 https://e5.qyi.io/outlook/auth2/receive 这个吗？
写错了也会报错

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'df6f86bd-1a9b-48b1-b25b-ea6520eec36f'. Trace ID: 6d7738e2-0c18-4151-b800-d6a7a6f94b00 Correlation ID: a8dc8d24-13c9-4d6d-99c2-c17a3b6f76ce Timestamp: 2021-04-02 15:15:16Z

**Comment by luoye663** [comment]
你是自己搭建的话写你的地址

**Comment by tkfanswind** [comment]
就是用你的服务器。我填写的 重定向  是 https://e5.qyi.io/outlook/auth2/receive
授权时候报错
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'df6f86bd-1a9b-48b1-b25b-ea6520eec36f'. Trace ID: 6d7738e2-0c18-4151-b800-d6a7a6f94b00 Correlation ID: a8dc8d24-13c9-4d6d-99c2-c17a3b6f76ce Timestamp: 2021-04-02 15:15:16Z

**Comment by luoye663** [comment]
我在数据库中没有找到你的应用id(df6f86bd-1a9b-48b1-b25b-ea6520eec36f)，不过这个问题确实是重定向填错了。
你授权的应用id是？

**Comment by tkfanswind** [comment]
文档没写填啥返回uri
我是自己猜的

**Comment by luoye663** [comment]
https://qyi.io/archives/687.html

**Comment by tkfanswind** [comment]
找到了。成功了。感谢
