### ISSUE TITLE
提出BUG

### ISSUE THREAD

**Issue by xihale** [luoye663/e5#8]
新版的日志查询不了了
等了很久,都没出现日志,希望解决!!!

**Comment by luoye663** [comment]
我这里看是正常，你的应用id随便发我一个看看

**Comment by xihale** [comment]
又看得到了,可能是我配置的问题吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月3日(星期六) 晚上11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [luoye663/e5] 提出BUG (#8)





 
我这里看是正常，你的应用id随便发我一个看看
